### ISSUE TITLE
System.OutOfMemoryException while creating Lookup creation

### ISSUE THREAD

**Issue by juhisharma21** [OHDSI/ETL-CDMBuilder#47]
Builder: oedmt-vm
Time: Jan  8 2019  5:51PM
Error: Exception Found:
Type: System.OutOfMemoryException
Message: Exception of type 'System.OutOfMemoryException' was thrown.
Source: org.ohdsi.cdm.framework.core
Stacktrace:    at org.ohdsi.cdm.framework.core.Lookups.MultiLookup.Add(IDataRecord reader, IDictionary`2 mLookup) in C:\Users\Public\Documents\ETL-CDMBuilder-master\source\Framework\org.ohdsi.cdm.framework.core\Lookups\MultiLookup.cs:line 72
   at org.ohdsi.cdm.framework.core.Lookups.MultiLookup.AddRecord(IDataReader reader) in C:\Users\Public\Documents\ETL-CDMBuilder-master\source\Framework\org.ohdsi.cdm.framework.core\Lookups\MultiLookup.cs:line 32
   at org.ohdsi.cdm.framework.core.Lookups.BaseLookup.Load() in C:\Users\Public\Documents\ETL-CDMBuilder-master\source\Framework\org.ohdsi.cdm.framework.core\Lookups\BaseLookup.cs:line 61
   at org.ohdsi.cdm.framework.core.Vocabulary.Load(String folder, IEnumerable`1 definitions) in C:\Users\Public\Documents\ETL-CDMBuilder-master\source\Framework\org.ohdsi.cdm.framework.core\Vocabulary.cs:line 254
   at org.ohdsi.cdm.framework.core.Vocabulary.Initialize() in C:\Users\Public\Documents\ETL-CDMBuilder-master\source\Framework\org.ohdsi.cdm.framework.core\Vocabulary.cs:line 156
   at org.ohdsi.cdm.framework.core.Controllers.BuilderController.<>c__DisplayClass33_0.<CreateLookup>b__0() in C:\Users\Public\Documents\ETL-CDMBuilder-master\source\Framework\org.ohdsi.cdm.framework.core\Controllers\BuilderController.cs:line 248
   at org.ohdsi.cdm.framework.core.Controllers.BuilderController.PerformAction(Action act) in C:\Users\Public\Documents\ETL-CDMBuilder-master\source\Framework\org.ohdsi.cdm.framework.core\Controllers\BuilderController.cs:line 79

Builder: oedmt-vm
Time: Jan  8 2019  2:31PM
Error: Exception Found:
Type: System.OutOfMemoryException
Message: Exception of type 'System.OutOfMemoryException' was thrown.
Source: mscorlib
Stacktrace:    at System.Number.FormatInt32(Int32 value, String format, NumberFormatInfo info)
   at System.Int32.ToString()
   at org.ohdsi.cdm.framework.core.Lookups.MultiLookup.Add(IDataRecord reader, IDictionary`2 mLookup) in C:\Users\vmadmin\Documents\ETL-CDMBuilder-master\source\Framework\org.ohdsi.cdm.framework.core\Lookups\MultiLookup.cs:line 38
   at org.ohdsi.cdm.framework.core.Lookups.MultiLookup.AddRecord(IDataReader reader) in C:\Users\vmadmin\Documents\ETL-CDMBuilder-master\source\Framework\org.ohdsi.cdm.framework.core\Lookups\MultiLookup.cs:line 32
   at org.ohdsi.cdm.framework.core.Lookups.BaseLookup.Load() in C:\Users\vmadmin\Documents\ETL-CDMBuilder-master\source\Framework\org.ohdsi.cdm.framework.core\Lookups\BaseLookup.cs:line 61
   at org.ohdsi.cdm.framework.core.Vocabulary.Load(String folder, IEnumerable`1 definitions) in C:\Users\vmadmin\Documents\ETL-CDMBuilder-master\source\Framework\org.ohdsi.cdm.framework.core\Vocabulary.cs:line 254
   at org.ohdsi.cdm.framework.core.Vocabulary.Initialize() in C:\Users\vmadmin\Documents\ETL-CDMBuilder-master\source\Framework\org.ohdsi.cdm.framework.core\Vocabulary.cs:line 164
   at org.ohdsi.cdm.framework.core.Controllers.BuilderController.<>c__DisplayClass33_0.<CreateLookup>b__0() in C:\Users\vmadmin\Documents\ETL-CDMBuilder-master\source\Framework\org.ohdsi.cdm.framework.core\Controllers\BuilderController.cs:line 248
   at org.ohdsi.cdm.framework.core.Controllers.BuilderController.PerformAction(Action act) in C:\Users\vmadmin\Documents\ETL-CDMBuilder-master\source\Framework\org.ohdsi.cdm.framework.core\Controllers\BuilderController.cs:line 79

**Comment by bradanton** [comment]
how much ram do you have?

**Comment by juhisharma21** [comment]
I have 16 GB RAM but when I changed the processor to be 64bit, then I am not getting this issue.
