### ISSUE TITLE
Exception while Copying Vocabulary

### ISSUE THREAD

**Issue by juhisharma21** [OHDSI/ETL-CDMBuilder#48]
Hi,

I am at the step of Copying Vocabulary part (5th step) and I am getting the following exception 

**Builder: oedmt-vm
Time: Jan 11 2019  1:58PM
Error: Exception Found:
Type: System.FormatException
Message: Input string was not in a correct format.
Source: mscorlib
Stacktrace:    at System.Text.StringBuilder.FormatError()
   at System.Text.StringBuilder.AppendFormatHelper(IFormatProvider provider, String format, ParamsArray args)
   at System.String.FormatHelper(IFormatProvider provider, String format, ParamsArray args)
   at System.String.Format(String format, Object arg0, Object arg1)
   at org.ohdsi.cdm.framework.data.DbLayer.DbDestination.CopyVocabulary(String query, String vocabularyConnectionString) in C:\Users\vmadmin\Documents\ETL-CDMBuilder-master\source\Framework\org.ohdsi.cdm.framework.data\DbLayer\DbDestination.cs:line 174
   at org.ohdsi.cdm.framework.core.Savers.MSSqlSaver.CopyVocabulary() in C:\Users\vmadmin\Documents\ETL-CDMBuilder-master\source\Framework\org.ohdsi.cdm.framework.core\Savers\MSSqlSaver.cs:line 66
   at org.ohdsi.cdm.framework.core.Controllers.BuilderController.<>c.<CopyVocabulary>b__30_0() in C:\Users\vmadmin\Documents\ETL-CDMBuilder-master\source\Framework\org.ohdsi.cdm.framework.core\Controllers\BuilderController.cs:line 213
   at org.ohdsi.cdm.framework.core.Controllers.BuilderController.PerformAction(Action act) in C:\Users\vmadmin\Documents\ETL-CDMBuilder-master\source\Framework\org.ohdsi.cdm.framework.core\Controllers\BuilderController.cs:line 79**

**Following is the code snippet that the exception is referring to** 

      public void CopyVocabulary(string query, string vocabularyConnectionString)
      {
         if (string.IsNullOrEmpty(query.Trim())) return;

         var vocab = new OdbcConnectionStringBuilder(vocabularyConnectionString);
         using (var connection = SqlConnectionHelper.OpenOdbcConnection(connectionString))
         {
            query = string.Format(query, vocab["server"], vocab["database"]);
            query = query.Replace("{sc}", schemaName);
            using (var command = new OdbcCommand(query, connection))
            {
               command.CommandTimeout = 0;
               command.ExecuteNonQuery();
            }
         }
      }

**Comment by bradanton** [comment]
this step is not critical, it just copying few tables.

the script for this step is here:
https://github.com/OHDSI/ETL-CDMBuilder/blob/master/bin/Common/MSSQL/v5.2/CopyVocabulary.sql

**Comment by juhisharma21** [comment]
Thanks @bradanton : I am trying to figure out the purpose of this step in the project, as this step is also followed by Indexes creation and post processes steps. How critical the step is .
