### ISSUE TITLE
Exception running Builder

### ISSUE THREAD

**Issue by JohnPCuthbert** [OHDSI/ETL-CDMBuilder#5]
I am running builder with the following settings:
Vendor: Cprd
Batches: 10
Batch size: 100
Parallelism: 2

I get this exception:
Exception Found:
Type: System.ArgumentNullException
Message: Value cannot be null.
Parameter name: format
Source: mscorlib
Stacktrace:    at System.String.Format(String format, Object arg0)
   at org.ohdsi.cdm.framework.data.DbLayer.DbSource.<GetPersonKeys>d__5.MoveNext() in c:\Users\john-c\Source\Repos\ETL-CDMBuilder\source\Framework\org.ohdsi.cdm.framework.data\DbLayer\DbSource.cs:line 58
   at org.ohdsi.cdm.framework.core.Controllers.ChunkController.<GetPersonKeys>d__5.MoveNext() in c:\Users\john-c\Source\Repos\ETL-CDMBuilder\source\Framework\org.ohdsi.cdm.framework.core\Controllers\ChunkController.cs:line 76
   at org.ohdsi.cdm.framework.core.Controllers.ChunkController.CreateChunks() in c:\Users\john-c\Source\Repos\ETL-CDMBuilder\source\Framework\org.ohdsi.cdm.framework.core\Controllers\ChunkController.cs:line 30
   at org.ohdsi.cdm.framework.core.Controllers.BuilderController.PerformAction(Action act) in c:\Users\john-c\Source\Repos\ETL-CDMBuilder\source\Framework\org.ohdsi.cdm.framework.core\Controllers\BuilderController.cs:line 72

**Comment by bradanton** [comment]
Try to rebuild project, seems that Batch.sql file not created.
You also, can check
{BuilderFolder}/CPRD/Batch.sql  -  file must exists

you can find builder folder in Builder db, SELECT [Folder] FROM [Builder]
