### ISSUE TITLE
any plans to support v6?

### ISSUE THREAD

**Issue by vojtechhuser** [OHDSI/ETL-CDMBuilder#52]
also, the Cerner HealthFacts ETL targets only 5.1

**Comment by clairblacketer** [comment]
We are moving all documentation over to our new github location (https://github.com/OHDSI/ETL-LambdaBuilder). We created a new location because the builder is new in that it uses AWS lambda and spectrum. All documentation will be here (https://ohdsi.github.io/ETL-LambdaBuilder/docs/CPRD). Right now it supports v5.3.1 but v6.0 is in development for all CDMs.

Cerner healthfacts only targets 5.1 because we no longer license that dataset so we did not update the version.

**Comment by jcabrerazuniga** [comment]
@clairblacketer : Is there a way to avoid using AWS for the https://github.com/OHDSI/ETL-LambdaBuilder? I tried running the 

org.ohdsi.cdm.presentation.builderprocess2.exe

with no parameters but entering my local DB settings yet I got an error like:
Builder: HSC-CTSC-ETL
Time: Nov 10 2020  9:39PM
Error: Exception Found:
Type: System.Data.SqlClient.SqlException
Message: Timeout expired.  The timeout period elapsed prior to completion of the operation or the server is not responding.
Timeout expired.  The timeout period elapsed prior to completion of the operation or the server is not responding.
Source: Core .Net SqlClient Data Provider
Stacktrace:    at System.Data.SqlClient.SqlConnection.OnError(SqlException exception, Boolean breakConnection, Action`1 wrapCloseInAction)
   at System.Data.SqlClient.TdsParser.ThrowExceptionAndWarning(TdsParserStateObject stateObj, Boolean callerHasConnectionLock, Boolean asyncClose)
   at System.Data.SqlClient.TdsParserStateObject.ReadSniError(TdsParserStateObject stateObj, UInt32 error)
   at System.Data.SqlClient.TdsParserStateObject.ReadSniSyncOverAsync()
   at System.Data.SqlClient.TdsParserStateObject.TryReadNetworkPacket()
   at System.Data.SqlClient.TdsParserStateObject.TryPrepareBuffer()
   at System.Data.SqlClient.TdsParserStateObject.TryReadByte(Byte& value)
   at System.Data.SqlClient.TdsParser.TryRun(RunBehavior runBehavior, SqlCommand cmdHandler, SqlDataReader dataStream, BulkCopySimpleResultSet bulkCopyHandler, TdsParserStateObject stateObj, Boolean& dataReady)
   at System.Data.SqlClient.TdsParser.Run(RunBehavior runBehavior, SqlCommand cmdHandler, SqlDataReader dataStream, BulkCopySimpleResultSet bulkCopyHandler, TdsParserStateObject stateObj)
   at System.Data.SqlClient.TdsParser.ProcessAttention(TdsParserStateObject stateObj)
   at System.Data.SqlClient.TdsParserStateObject.WriteSni(Boolean canAccumulate)
   at System.Data.SqlClient.TdsParserStateObject.WritePacket(Byte flushMode, Boolean canAccumulate)
   at System.Data.SqlClient.TdsParser.WriteLong(Int64 v, TdsParserStateObject stateObj)
   at System.Data.SqlClient.TdsParser.WriteUnterminatedValue(Object value, MetaType type, Byte scale, Int32 actualLength, Int32 encodingByteSize, Int32 offset, TdsParserStateObject stateObj, Int32 paramSize, Boolean isDataFeed)
   at System.Data.SqlClient.TdsParser.WriteBulkCopyValue(Object value, SqlMetaDataPriv metadata, TdsParserStateObject stateObj, Boolean isSqlType, Boolean isDataFeed, Boolean isNull)
   at System.Data.SqlClient.SqlBulkCopy.ReadWriteColumnValueAsync(Int32 col)
   at System.Data.SqlClient.SqlBulkCopy.CopyColumnsAsync(Int32 col, TaskCompletionSource`1 source)
   at System.Data.SqlClient.SqlBulkCopy.CopyRowsAsync(Int32 rowsSoFar, Int32 totalRows, CancellationToken cts, TaskCompletionSource`1 source)
   at System.Data.SqlClient.SqlBulkCopy.CopyBatchesAsyncContinued(BulkCopySimpleResultSet internalResults, String updateBulkCommandText, CancellationToken cts, TaskCompletionSource`1 source)
   at System.Data.SqlClient.SqlBulkCopy.CopyBatchesAsync(BulkCopySimpleResultSet internalResults, String updateBulkCommandText, CancellationToken cts, TaskCompletionSource`1 source)
   at System.Data.SqlClient.SqlBulkCopy.WriteToServerInternalRestContinuedAsync(BulkCopySimpleResultSet internalResults, CancellationToken cts, TaskCompletionSource`1 source)
   at System.Data.SqlClient.SqlBulkCopy.WriteToServerInternalRestAsync(CancellationToken cts, TaskCompletionSource`1 source)
   at System.Data.SqlClient.SqlBulkCopy.WriteToServerInternalAsync(CancellationToken ctoken)
   at System.Data.SqlClient.SqlBulkCopy.WriteRowSourceToServerAsync(Int32 columnCount, CancellationToken ctoken)
   at System.Data.SqlClient.SqlBulkCopy.WriteToServer(IDataReader reader)
   at org.ohdsi.cdm.framework.desktop.Savers.Saver.AddChunk(List`1 chunk, Int32 index)
  Inner Exception Found:
  Type: System.ComponentModel.Win32Exception
  Message: The wait operation timed out
  Source:
  Stacktrace:

When I started running the previous app I saw:

Chunks creation in progress, please do not close the window...
Bucket =;CDMFolder=cdm
SaveOnlyToS3=True; StorageType=Parquet;
Settings initialized
Vendor=Truven_CCAE; restart=False
BuildingId=1; Chunk size=512
Source connection string=Driver={SQL Server Native Client 11.0};Server=localhost;Database=Truven_ccae

Is the **no use** of AWS documented somewhere? At my university we got our own Truven server and we do not want to pay for AWS. 
Thanks
Jose

**Comment by bradanton** [comment]
> @clairblacketer : Is there a way to avoid using AWS for the https://github.com/OHDSI/ETL-LambdaBuilder? I tried running the
> 
> org.ohdsi.cdm.presentation.builderprocess2.exe
> 
> with no parameters but entering my local DB settings yet I got an error like:
> Builder: HSC-CTSC-ETL
> Time: Nov 10 2020 9:39PM
> Error: Exception Found:
> Type: System.Data.SqlClient.SqlException
> Message: Timeout expired. The timeout period elapsed prior to completion of the operation or the server is not responding.
> Timeout expired. The timeout period elapsed prior to completion of the operation or the server is not responding.
> Source: Core .Net SqlClient Data Provider
> Stacktrace: at System.Data.SqlClient.SqlConnection.OnError(SqlException exception, Boolean breakConnection, Action`1 wrapCloseInAction) at System.Data.SqlClient.TdsParser.ThrowExceptionAndWarning(TdsParserStateObject stateObj, Boolean callerHasConnectionLock, Boolean asyncClose) at System.Data.SqlClient.TdsParserStateObject.ReadSniError(TdsParserStateObject stateObj, UInt32 error) at System.Data.SqlClient.TdsParserStateObject.ReadSniSyncOverAsync() at System.Data.SqlClient.TdsParserStateObject.TryReadNetworkPacket() at System.Data.SqlClient.TdsParserStateObject.TryPrepareBuffer() at System.Data.SqlClient.TdsParserStateObject.TryReadByte(Byte& value) at System.Data.SqlClient.TdsParser.TryRun(RunBehavior runBehavior, SqlCommand cmdHandler, SqlDataReader dataStream, BulkCopySimpleResultSet bulkCopyHandler, TdsParserStateObject stateObj, Boolean& dataReady) at System.Data.SqlClient.TdsParser.Run(RunBehavior runBehavior, SqlCommand cmdHandler, SqlDataReader dataStream, BulkCopySimpleResultSet bulkCopyHandler, TdsParserStateObject stateObj) at System.Data.SqlClient.TdsParser.ProcessAttention(TdsParserStateObject stateObj) at System.Data.SqlClient.TdsParserStateObject.WriteSni(Boolean canAccumulate) at System.Data.SqlClient.TdsParserStateObject.WritePacket(Byte flushMode, Boolean canAccumulate) at System.Data.SqlClient.TdsParser.WriteLong(Int64 v, TdsParserStateObject stateObj) at System.Data.SqlClient.TdsParser.WriteUnterminatedValue(Object value, MetaType type, Byte scale, Int32 actualLength, Int32 encodingByteSize, Int32 offset, TdsParserStateObject stateObj, Int32 paramSize, Boolean isDataFeed) at System.Data.SqlClient.TdsParser.WriteBulkCopyValue(Object value, SqlMetaDataPriv metadata, TdsParserStateObject stateObj, Boolean isSqlType, Boolean isDataFeed, Boolean isNull) at System.Data.SqlClient.SqlBulkCopy.ReadWriteColumnValueAsync(Int32 col) at System.Data.SqlClient.SqlBulkCopy.CopyColumnsAsync(Int32 col, TaskCompletionSource`1 source)
> at System.Data.SqlClient.SqlBulkCopy.CopyRowsAsync(Int32 rowsSoFar, Int32 totalRows, CancellationToken cts, TaskCompletionSource`1 source) at System.Data.SqlClient.SqlBulkCopy.CopyBatchesAsyncContinued(BulkCopySimpleResultSet internalResults, String updateBulkCommandText, CancellationToken cts, TaskCompletionSource`1 source)
> at System.Data.SqlClient.SqlBulkCopy.CopyBatchesAsync(BulkCopySimpleResultSet internalResults, String updateBulkCommandText, CancellationToken cts, TaskCompletionSource`1 source) at System.Data.SqlClient.SqlBulkCopy.WriteToServerInternalRestContinuedAsync(BulkCopySimpleResultSet internalResults, CancellationToken cts, TaskCompletionSource`1 source)
> at System.Data.SqlClient.SqlBulkCopy.WriteToServerInternalRestAsync(CancellationToken cts, TaskCompletionSource`1 source) at System.Data.SqlClient.SqlBulkCopy.WriteToServerInternalAsync(CancellationToken ctoken) at System.Data.SqlClient.SqlBulkCopy.WriteRowSourceToServerAsync(Int32 columnCount, CancellationToken ctoken) at System.Data.SqlClient.SqlBulkCopy.WriteToServer(IDataReader reader) at org.ohdsi.cdm.framework.desktop.Savers.Saver.AddChunk(List`1 chunk, Int32 index)
> Inner Exception Found:
> Type: System.ComponentModel.Win32Exception
> Message: The wait operation timed out
> Source:
> Stacktrace:
> 
> When I started running the previous app I saw:
> 
> Chunks creation in progress, please do not close the window...
> Bucket =;CDMFolder=cdm
> SaveOnlyToS3=True; StorageType=Parquet;
> Settings initialized
> Vendor=Truven_CCAE; restart=False
> BuildingId=1; Chunk size=512
> Source connection string=Driver={SQL Server Native Client 11.0};Server=localhost;Database=Truven_ccae
> 
> Is the **no use** of AWS documented somewhere? At my university we got our own Truven server and we do not want to pay for AWS.
> Thanks
> Jose

Hi Jose,

I just committed new version. Will works without AWS.

https://github.com/OHDSI/ETL-CDMBuilder/tree/master/source
https://github.com/OHDSI/ETL-CDMBuilder/tree/master/executable
